# Generated by Django 3.1 on 2020-12-29 08:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Catogery',
            fields=[
                ('catogery_id', models.AutoField(primary_key=True, serialize=False)),
                ('catogery_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(blank=True, default=1, null=True)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('address', models.CharField(default='', max_length=150)),
                ('phone', models.CharField(default='', max_length=150)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('product_sku', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('registered_date', models.DateField()),
                ('productimage', models.ImageField(default='/default/default.png', upload_to='shop/images')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brand')),
                ('catogery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.catogery')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='catogery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.catogery'),
        ),
    ]
