# Generated by Django 3.1 on 2020-12-29 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('product_sku', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('registered_date', models.DateField()),
                ('productimage', models.ImageField(default='/default/default.png', upload_to='shop/images')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brand')),
                ('catogery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.catogery')),
            ],
        ),
    ]
