# Generated by Django 3.1 on 2020-12-29 08:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_shopproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOrders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('address', models.CharField(default='', max_length=150)),
                ('phone', models.CharField(default='', max_length=150)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(to='shop.ShopProduct')),
            ],
        ),
    ]
