# Generated by Django 3.1 on 2020-12-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shoporders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='catogery',
        ),
        migrations.RemoveField(
            model_name='product',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
