# Generated by Django 3.1 on 2020-12-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productquantity',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
