# Generated by Django 3.1 on 2020-12-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productquantity_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporders',
            name='iscompleted',
            field=models.BooleanField(default=False),
        ),
    ]
